### ISSUE TITLE
Investigate published contents

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-SDK#9]
When publishing an update to npm, I just noticed that the tarball includes all the sourcemap files. For bundle size reasons, we should think about whether these are worth keeping inside our published package.

**Comment by michaelgira23** [comment]
I believe I purposefully left sourcemap files in the npm package so that we could easily debug when developing the frontend or any other client. The thought process was that the npm bundle size is not as important because Angular and other build processes should already remove sourcemaps for production builds.

**Comment by nickbclifford** [comment]
Gotcha, makes sense.
